import turtle
import turtle as tur
import time
try:
  wn = turtle. Screen()
  wn. setup(800, 800)
  wn. bgcolor("black")
  wn. title("ye")
except:
    print("no work")
ap = turtle.Turtle()
movmint =('W = forword | L = left | R = right | pre = list of the pre sets')
presets =('circle | square | jesus | jesus3D |')

print('type log to see controls')
while True:
  pp = input('input:')
  num = ('log', 'W', 'R', 'L', 'penup', 'pendown', 'color', 'circle', 'pre', 'square')
  available_pp = [num]
  while pp == 'color':
    color = input('tipe color:')
    ap = turtle.color([color])
    pp = input('input:')
  if pp == 'pre':
    print(presets)
  if pp == 'log':#pynput
    print(movmint)
  if pp == 'w':
    ap = turtle.forward(5)
  if pp == 'r':
    ap = turtle.right(45)
  if pp == 'l':
    ap = turtle.left(45)
  if pp == 'penup':
    ap = turtle.penup()
  if pp == "pendown":
    ap = turtle.pendown()
  if pp == 'circle':
    ap = turtle.forward(20)
    ap = turtle.right(45)
    ap = turtle.forward(15)
    ap = turtle.right(45)
    ap = turtle.forward(20)
    ap = turtle.right(45)
    ap = turtle.forward(15)
    ap = turtle.right(45)
    ap = turtle.forward(20)
    ap = turtle.right(45)
    ap = turtle.forward(15)
    ap = turtle.right(45)
    ap = turtle.forward(20)
    ap = turtle.right(45)
    ap = turtle.forward(15)
    ap = turtle.right(45)
  if pp == 'square':
    ap = turtle.forward(20)
    ap = turtle.right(90)
    ap = turtle.forward(20)
    ap = turtle.right(90)
    ap = turtle.forward(20)
    ap = turtle.right(90)
    ap = turtle.forward(20)
    ap = turtle.right(90)
  if pp == 'jesus':
    ap = turtle.forward(7)
    ap = turtle.left(90)
    ap = turtle.forward(35)
    ap = turtle.right(90)
    ap = turtle.forward(12.5)
    ap = turtle.left(90)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(12.5)
    ap = turtle.right(90)
    ap = turtle.forward(15)
    ap = turtle.left(90)
    ap = turtle.forward(7)
    ap = turtle.left(90)
    ap = turtle.forward(15)
    ap = turtle.right(90)
    ap = turtle.forward(12.5)
    ap = turtle.left(92)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(12.5)
    ap = turtle.right(92)
    ap = turtle.forward(35)
    ap = turtle.left(90)
  if pp == 'jesus3D':
    ap = turtle.forward(7)
    ap = turtle.left(90)
    ap = turtle.forward(35)
    ap = turtle.right(90)
    ap = turtle.forward(12.5)
    ap = turtle.left(90)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(12.5)
    ap = turtle.right(90)
    ap = turtle.forward(15)
    ap = turtle.left(90)
    ap = turtle.forward(7)
    ap = turtle.left(90)
    ap = turtle.forward(15)
    ap = turtle.right(90)
    ap = turtle.forward(12.5)
    ap = turtle.left(92)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(12.5)
    ap = turtle.right(92)
    ap = turtle.forward(35)
    ap = turtle.left(90)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(5*7)
    ap = turtle.right(90)
    ap = turtle.forward(12)
    ap = turtle.left(90)
    ap = turtle.forward(10)
    ap = turtle.left(90)
    ap = turtle.forward(12)
    ap = turtle.right(90)
    ap = turtle.forward(15)
    ap = turtle.left(90)
    ap = turtle.forward(3)
  if pp != [num]:
    print('stop experiminting')
    print(movmint)
    print(presets)
